version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: hamza-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: hamza
      MYSQL_USER: hamza
      MYSQL_PASSWORD: hamza1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hamza-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hamza?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: hamza
      SPRING_DATASOURCE_PASSWORD: hamza1234
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data: 