spring:
  application:
    name: hamza
  
  profiles:
    active: dev
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  sql:
    init:
      mode: never

  

  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# External API Configuration
external-api:
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-3.5-turbo
    max-tokens: 150
    temperature: 0.7
  
  google:
    api-key: ${GOOGLE_MAPS_API_KEY}
    places-url: https://maps.googleapis.com/maps/api/place/nearbysearch/json
    geocoding-url: https://maps.googleapis.com/maps/api/geocode/json

# Application Configuration
app:
  base-url: https://be0ee3a02f69.ngrok-free.app
  # CORS 설정은 SecurityConfig에서 통합 관리하므로 여기서는 제거

# Rate Limiting Configuration
rate-limiting:
  enabled: true
  requests-per-minute: 60
  requests-per-hour: 1000
  chat-requests-per-minute: 10
  diagnosis-requests-per-hour: 5
  
  diagnosis:
    phq9:
      normal: 4
      mild: 9
      moderate: 14
      severe: 19
    retest-interval: 7 # days
  
  treatment:
    session-duration: 600 # seconds (10 minutes)
    max-sessions-per-day: 5
  
  hospital:
    search-radius: 10 # km
    max-results: 20
  
  chatbot:
    crisis-keywords:
      - "자살"
      - "죽고싶어"
      - "포기"
      - "절망"
      - "죽음"
    emergency-contact: "1588-9191"

# Logging Configuration
logging:
  level:
    com.dgsw.hamza: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/restart-clinic.log
    max-size: 10MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
    httptrace:
      enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms
    tags:
      application: hamza
      environment: ${spring.profiles.active:dev}

# Server Configuration
server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework
  use-forward-headers: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
  
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    csrf:
      enabled: false
    cors:
      enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
  show-actuator: true
  group-configs:
    - group: "hamza-api"
      paths-to-match: "/api/**"
      packages-to-scan: com.dgsw.hamza.controller